version: '3.8'

services:
  backend:
    build: ./url-shortener-backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build: ./url-shortener-frontend
    ports:
      - '3000:80'

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
